services:
  registry:
    image: registry:2
    environment:
        REGISTRY_HTTP_ADDR: 0.0.0.0:443
        REGISTRY_AUTH: htpasswd
        REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
        REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
        REGISTRY_HTTP_TLS_KEY: /certs/registry.key
    ports:
      - 5000:5000
      - 443:443
    networks:
      registry:
        aliases:
          - formation.lan
    volumes:
      - ./certs:/certs:ro
      - ./auth:/auth:ro
      - registry:/var/lib/registry
    deploy:
      endpoint_mode: vip
      mode: replicated # 1 replica unique dans chaque noeud
      placement:
        constraints:
          # logique AND sur plusieurs contraintes
          - node.role == manager
          - node.platform.os == linux
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 2

networks:
  registry:
    name: registry
    driver: overlay

volumes:
  registry:
    name: registry