---
version: '3.9'

#  {
#     "version":"3.9",
#     "services":{
#       "app_nginx": {
#         "container_name": "app_nginx", 
#         ..., 
#         "ports": [
#           "8080:80", ...
#         ]
#       }
#     }
#   }

services:
  # nom d'un service arbitraire
  app_nginx:
    container_name: app_nginx
    image: nginx:1.25.4
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - stack_php
    volumes:
      - /vagrant/php8.2.conf:/etc/nginx/conf.d/php8.2.conf
    depends_on:
      - app_php
    profiles:
      - stack
    # healthcheck: "commande de test"
  
  app_php:
    container_name: app_php
    restart: unless-stopped
    networks:
      - stack_php
    volumes:
      - /vagrant/index.php:/srv/index.php
    image: bitnami/php-fpm:8.2-debian-11
    # on ne peut lancer le service qu'après le(s) service(s) renseigné(s)
    depends_on:
      - app_mariadb
    # partitionnement de services dans la "liste" des services 
    # - stack pour fabriquer le microservice
    # - backup pour demander un export (one shot)
    profiles:
      - stack

  app_mariadb:
    container_name: app_mariadb
    restart: unless-stopped
    env_file:
      - /vagrant/.env
    networks:
      - stack_php
    volumes:
      - db_data:/var/lib/mysql
      - /vagrant/mariadb-init.sql:/docker-entrypoint-initdb.d/mariadb-init.sql
    image: mariadb:10.11.6
    profiles:
      - stack
      - backup
  
  # on peut l'utiliser en onshot avec docker compose run --rm backup (nom du service)
  # on peut utiliser le compose run comme le docker run normal i.e avec une commande particulière
  backup:
    image: debian:12-slim
    container_name: backup
    volumes:
      - /vagrant/backup:/backup
    # le container n'a pas de réseau
    network_mode: none
    # raccrocher les volumes d'un ou d' autres services
    volumes_from:
      - app_mariadb
    # commande au lancement du container
    command: tar -czvf /backup/backup.gz /var/lib/mysql
    depends_on:
      - app_mariadb
    profiles:
      - backup

networks:
  stack_php:
    name: stack_app
    driver: bridge
    ipam:
      # {"config": [{"subnet": ..., "gateway"}, ...]}
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

      


volumes:
  db_data:
    name: db_data