---
version: '3'

services:
  registry:
    image: registry:2    
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry.key
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    ports:
      - 5000:5000
      - 443:443
    networks:
      - registry
    volumes:
      - /vagrant/registry/certs:/certs:ro
      - /vagrant/registry/auth:/auth
    deploy:
      # balance loading interne dans les noeud (Virtual IP)
      # autre possibilité avec un loading balancer extérieur (HAproxy) (dnsrr => dns Round Robin)
      endpoint_mode: vip
      # replicated: placées de façon random
      # global: une instance par noeud
      mode: replicated
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 2
      # gestion des rolling update
      update_config:
        parallelism: 2

networks:
  registry:
    name: registry
    driver: overlay
  